apis:
  service.core-api:
    name: Core API
    prefix: api/rpi
    upstream_url: http://service.core-api
    allow_cross_origin: true

  service.sensor-controller:
    name: Sensor Controller Service
    prefix: api/sensor-controller
    upstream_url: http://service.sensor-controller
    allow_cross_origin: true

  service.calibration:
    name: Calibration Service
    prefix: api/calibration
    upstream_url: http://service.calibration
    allow_cross_origin: true
    
  service.data-upload:
    name: Data Upload Service
    prefix: api/data-upload
    upstream_url: http://service.data-upload
    allow_cross_origin: true
