version: "3.5"

services:
  web-client:
    build:
      context: ./web-client
      dockerfile: prod.dockerfile
    env_file: ./.env
    image: portable-force-rig/web-client:1.0
    container_name: web-client
    ports:
      - 7000:80
    volumes:
      - ./web-client/build:/usr/share/nginx/html
      - ./web-client/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./service.video-stream/recordings:/usr/share/nginx/html/recordings

  service.api-gateway:
    image: portable-force-rig/drawbridge:1.0
    env_file: ./.env
    container_name: service.api-gateway
    volumes:
      - ./service.api-gateway/config.yaml:/config/config.yaml
    ports:
      - 7001:80

  service.event-bus:
    build: ./service.event-bus
    env_file: ./.env
    image: portable-force-rig/service.event-bus:1.0
    container_name: service.event-bus
    depends_on:
      - redis
    ports:
      - 7002:80
    volumes:
      - ./service.event-bus:/usr/src/app
      - /usr/src/app/node_modules

  service.core-api:
    build: ./service.core-api
    env_file: ./.env
    image: portable-force-rig/service.core-api:1.0
    container_name: service.core-api
    ports:
      - 7003:80
    volumes:
      - ./service.core-api:/usr/src/app
      - /usr/src/app/node_modules
      - type: bind
        source: ./data/readings.sqlite
        target: /usr/src/app/data/readings.sqlite

  service.sensor-controller:
    build: ./service.sensor-controller
    env_file: ./.env
    image: portable-force-rig/service.sensor-controller:1.0
    container_name: service.sensor-controller
    depends_on:
      - redis
    ports:
      - 7004:80
    volumes:
      - ./service.sensor-controller:/usr/src/app
      - type: bind
        source: ./service.calibration/lookup.npy
        target: /usr/src/app/lookup.npy
    privileged: true


  service.data-upload:
    build: ./service.data-upload
    env_file: ./.env
    image: portable-force-rig/service.data-upload:1.0
    container_name: service.data-upload
    ports:
      - 7005:80
    volumes:
      - ./service.data-upload:/usr/src/app
      - type: bind
        source: ./data/readings.sqlite
        target: /usr/src/app/data/readings.sqlite

  # service.calibration:
  #   build: ./service.calibration
  #   env_file: ./.env
  #   image: portable-force-rig/service.calibration:1.0
  #   container_name: service.calibration
  #   ports:
  #     - 7006:80
  #   volumes:
  #     - ./service.calibration:/usr/src/app
  #   privileged: true

  redis:
    image: redis:alpine
    env_file: ./.env
    container_name: redis-server
    ports:
      - 6379:6379
